default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>

development:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  database: diary_app_development

test:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  database: diary_app_test

production:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  database: <%= ENV.fetch("POSTGRES_DB", "diary_app_production") %>
  url: <%= ENV["DATABASE_URL"] %>
